version: '3.1'

# 컴퓨터들
services:

  backend-c:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
    ports:
      - 4000:4000

  database-c:
    image: mongo:5
    ports:
      - 27017:27017