services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/backend/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  database:
    # platform: linux/86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "dockerProject"
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
